name = "hello-kv"
compatibility_date = "2024-07-01"
main = "src/index.ts"

[[kv_namespaces]]
binding = "KV"
id = "3e1507ad454641428464895dec6af234"

# [vars]
# MY_VAR = "my-variable"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

#[[d1_databases]]
#binding = "MY_DB"
#database_name = "my-database"
#database_id = ""

# [ai]
# binding = "AI"