name = "embedding-hello-world"
compatibility_date = "2024-07-01"
main = "src/index.ts"

[ai]
binding = "AI"

# [vars]
# MY_VAR = "my-variable"

#[[kv_namespaces]]
#binding = "MY_KV_NAMESPACE"
#id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

#[[d1_databases]]
#binding = "MY_DB"
#database_name = "my-database"
#database_id = ""

